font_family Monocraft
font_size 9.0
disable_ligatures never

cursor_shape beam
cursor_trail 1

confirm_os_window_close 0
enable_audio_bell no

shell fish

# For nvim control over terminal
allow_remote_control yes
listen_on unix:@mykitty

resize_in_steps yes

# font_family IosevkaCode
# font_size 10.0

font_family Monocraft
font_size 9.0

disable_ligatures never

background_opacity 1.00
window_padding_width 10
selection_foreground #8080FF
selection_background #000040

input_delay 1
repaint_delay 2


map ctrl+c    copy_or_interrupt
map ctrl+shift+u        input_unicode_character

cursor #ffffff
