add_newline = false
palette = "cyber"

format = """
[╭─](dark_gray)\
([❰](dark_gray) \
$shlvl$package\
$deno$bun$nodejs$lua$python$ruby$rust$swift$aws$buf$c$cpp$conda$pixi$dart$elixier$elm$golang$haskell$java$julia$nim$nix_shell$spack\
[❱](dark_gray))$fill[─](dark_gray)\
([❰](dark_gray) \
$docker_context$git_branch$git_metrics\
[❱](dark_gray))[─](dark_gray)
[╰─(❰$cmd_duration)❱](dark_gray)\
$directory$character
"""

right_format = ""

[palettes.cyber]
gray = "#555555"
dark_gray = "#282828"
neon_magenta = "#ff00ff"
neon_cyan = "#00ffff"
neon_green = "#39ff14"

git = "#f05032"
docker = "#0088ee"

deno = "#ffffff"
lua = "#0088ee"
nodejs = "#339933"
bun = "#f9ea88"
python = "#4b8bbe"
ruby = "#cc342d"
rust = "#ff6030"
swift = "#f05138"
aws = "#ff9900"
buf = "#0077ff"
c = "#a8b9cc"
cpp = "#007acc"
conda = "#43b02a"
pixi = "#f2c200"
dart = "#0175c2"
elixir = "#a26bff"
elm = "#60b5cc"
golang = "#00add8"
haskell = "#8f4ce0"
java = "#e76f00"
julia = "#9558b2"
nim = "#ffe953"
nix = "#7ab1e5"
spack = "#0091ea"

[fill]
style = 'fg:dark_gray'
symbol = '─'

[directory]
format = '[🭮](dark_gray)[$path](fg:$style bg:dark_gray)[▌](dark_gray)'
style = "neon_cyan"
truncate_to_repo = true
truncation_length = 8
truncation_symbol = '❰/'

[character]
format         = "$symbol"
success_symbol  = "[ I ](bold fg:#000000 bg:#00d85f)[🭬](#00d85f)"
error_symbol  = "[ E ](bold fg:#000000 bg:#ff0033)[🭬](#ff0033)"
vimcmd_symbol  = "[ N ](bold fg:#000000 bg:#00d4ff)[🭬](fg:#00d4ff)"

[cmd_duration]
format = "[$duration](neon_cyan)"

[shlvl]
disabled = false
format = '[$symbol$shlvl](bold neon_cyan) '
symbol = ""
threshold = 3

[package]
format = '[at](gray) [$version](bold neon_magenta) '

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style) '
symbol = " " 
style = "bold neon_magenta"
truncation_length = 6
truncation_symbol = '…'
# only_attached = true
ignore_branches = []

[git_metrics]
format = '([▴$added]($added_style))([▿$deleted]($deleted_style)) '
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = false

[docker_context]
format = "[in](gray) [docker](docker) [$context](neon_magenta)"

[deno]
format = '[via](gray) [deno](bold deno) [$version](bold neon_magenta) '
version_format = "${raw}"

[lua]
format = '[via](gray) [lua](bold lua) [$version](bold neon_magenta) '
version_format = "${raw}"

[nodejs]
format = '[via](gray) [node](bold nodejs) [$version](bold neon_magenta) '
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[bun]
format = '[via](gray) [bun](bold bun) [$version](bold neon_magenta) '
version_format = "${raw}"

[python]
format = '[via](gray) [python](bold python) [$version](bold neon_magenta) '
version_format = "${raw}"

[ruby]
format = '[via](gray) [ruby](bold ruby) [$version](bold neon_magenta) '
version_format = "${raw}"

[rust]
format = '[via](gray) [rust](bold rust) [$version](bold neon_magenta) '
version_format = "${raw}"

[swift]
format = '[via](gray) [swift](bold swift) [$version](bold neon_magenta) '
version_format = "${raw}"

[aws]
disabled = true
format = '[via](gray) [aws](bold aws) [$profile $region](bold neon_magenta) '

[buf]
format = '[via](gray) [buf](bold buf) [$version](bold neon_magenta) '

[c]
format = '[via](gray) [C](bold c) [$version(-$name)](bold neon_magenta) '

[cpp]
format = '[via](gray) [C++](bold cpp) [$version(-$name)](bold neon_magenta) '

[conda]
format = '[via](gray) [conda](bold conda) [$environment](bold neon_magenta) '

[pixi]
format = '[via](gray) [pixi](bold pixi) [$version](bold neon_magenta) ([$environment](gray) ) '

[dart]
format = '[via](gray) [dart](bold dart) [$version](bold neon_magenta) '
version_format = "${raw}"

[elixir]
format = '[via](gray) [elixir](bold elixir) [$version](bold neon_magenta) ([OTP $otp_version](italic gray) ) '
version_format = "${raw}"

[elm]
format = '[via](gray) [elm](bold elm) [$version](bold neon_magenta) '
version_format = "${raw}"

[golang]
format = '[via](gray) [go](bold golang) [$version](bold neon_magenta) '
version_format = "${raw}"

[haskell]
format = '[via](gray) [haskell](bold haskell) [$version](bold neon_magenta) '
version_format = "${raw}"

[java]
format = '[via](gray) [java](bold java) [$version](bold neon_magenta) '
version_format = "${raw}"

[julia]
format = '[via](gray) [julia](bold julia) [$version](bold neon_magenta) '
version_format = "${raw}"

[nim]
format = '[via](gray) [nim](bold nim) [$version](bold neon_magenta) '
version_format = "${raw}"

[nix_shell]
format = '[via](gray) [nix](bold nix) $state ([$name](italic gray) ) '
impure_msg = '[⌽](bold dimmed neon_magenta)'
pure_msg = '[⌾](bold dimmed neon_green)'
unknown_msg = '[◌](bold dimmed neon_cyan)'

[spack]
format = '[via](gray) [spack](bold spack) [$environment](bold neon_magenta) '
